BlockHandler과 BlockComponent 리팩토링 및 수정요청 사항 반영
boostcamp-2020/Project18-C-Bootion pull request #50
Opened 2020-11-30 12:37 UTC by domino8788

# BlockHandler 리팩토링 및 수정요청 사항 반영

## 해당 이슈 📎

#39 #44

## 변경 사항 🛠

구현내용 요약

- BlockHandler 리팩토링
- BlockComponent 리팩토링
- page store 구현
- 불필요한 파일 제거
- 변경사항에 따른 서식 조정

## 테스트 ✨

없음

## 리뷰어 참고 사항 🙋‍♀️

2020-11-30 19:14 UTC, skid901 requested changes
코드 리팩토링 진행하시느라 정말 고생 많으셨습니다!!
몇 가지 개인 의견을 남겼습니다.
공감되는 부분이 있으시면 적용 후 머지 하시면 될 것 같아요!!

2020-11-30 19:14 UTC, skid901 commented on frontend/src/components/molecules/BlockComponent/BlockComponent.tsx
>    }, [blockRef.current?.clientWidth, blockRef.current?.clientHeight]);
아까 궁금한 점이 있었는데,
호버 영역을 자바스크립트 코드로 계산해 주는 방법 대신,
css 에서 `calc()` 를 통해 `%`(퍼센테이지)를 연산하는 방법으로
너비와 높이를 설정해 주는 방법은 적용하기 힘들까요?

2020-11-30 19:14 UTC, skid901 commented on frontend/src/components/molecules/HoverArea/HoverArea.tsx
> +function HoverArea(sizeInfo: ComponentSize): React.ReactElement {
호버 영역을 별도의 컴포넌트로 분리해서 코드가 매우 정갈해 진 것 같아요!!

2020-11-30 19:14 UTC, skid901 commented on frontend/src/stores/page.tsx
> +const hoveredBlockState = atom<number | string | null>({
type alias 를 통해 
```
type hoverInput = number | string | null;
```
대충 이런 느낌으로 `number | string | null`를 대체하는 타입을 지정하는 것도 좋을 것 같아요.

2020-12-01 00:28 UTC, domino8788 commented on frontend/.prettierrc
> -    "arrowParens": "always"
semi, useTabs, printWidth, arrowParens 의 설정값이 default 값이라는 review가 있었습니다.
prettier 공식문서를 통해 default 값임을 확인했기 때문에 삭제했습니다.

2020-12-01 01:37 UTC, YiSoJeong approved these changes
css 계산 부분도 더 리팩토링 가능하겠네용!!

2020-12-01 01:37 UTC, YiSoJeong commented on frontend/src/components/molecules/BlockComponent/BlockComponent.tsx
> -    </div>
분리한거 깔끔하고 좋아요~!

2020-12-01 01:37 UTC, YiSoJeong commented on frontend/src/components/molecules/BlockComponent/BlockComponent.tsx
> +    setHoveredBlockId(null);
state로 관리하니까 깔끔하네요🤩

2020-12-01 01:45 UTC, domino8788 commented on frontend/src/components/molecules/BlockComponent/BlockComponent.tsx
> +  };
ev를 사용할 일이 없으므로 ()=>{}로 수정 했습니다.

2020-12-01 01:46 UTC, domino8788 commented on frontend/src/components/molecules/BlockComponent/BlockComponent.tsx
>    }, [blockRef.current?.clientWidth, blockRef.current?.clientHeight]);
반영했습니다. 조언 감사합니다. :)

2020-12-01 01:46 UTC, domino8788 commented on frontend/src/components/molecules/HoverArea/HoverArea.tsx
> +function HoverArea(sizeInfo: ComponentSize): React.ReactElement {
칭찬 감사합니다 ㅎㅎㅎ

2020-12-01 02:14 UTC, domino8788 commented on frontend/src/stores/page.tsx
> +const hoveredBlockState = atom<number | string | null>({
반영했습니다.

2020-12-01 02:21 UTC, skid901 approved these changes
요청 반영해 주시느라 고생하셨습니다 ^^7

2020-12-01 02:21 UTC, merged