블록 타입에 따라 content가 변하는 로직 외부화
boostcamp-2020/Project18-C-Bootion pull request #63
Opened 2020-12-02 04:00 UTC by YiSoJeong

# 블록 타입에 따라 content가 변하는 로직 외부화

## 해당 이슈 📎

#32 #58 

## 변경 사항 🛠

블록의 내용에 따라 컴포넌트 타입이 변경되는 로직을 외부화 하였습니다.

## 테스트 ✨

없음

## 리뷰어 참고 사항 🙋‍♀️

[Block의 value를 useRef로 관리하는 이유](https://react.vlpt.us/basic/12-variable-with-useRef.html)
`state`로 관리하는 한 글자씩 변경될 때마다 리렌더링 되기 때문에
useRef에 초기값을 주는 방법으로 block의 value를 관리할 생각입니다 :)

아직 로직 외부화만 되어 있어 중복코드 해결은 하지 못했습니다 :(
이후 PR에서 바로 적용 시키겠습니다😊

2020-12-02 04:24 UTC, skid901 requested changes
고생하셨습니다 ^^7
필수 수정사항과 선택 수정사항 참고 부탁드립니다 ㅎㅎ

2020-12-02 04:24 UTC, skid901 commented on frontend/src/components/atoms/Text/index.ts
> +export { default } from './Text';
EOL 추가 부탁드립니다 ^^7

2020-12-02 04:24 UTC, skid901 commented on frontend/src/hooks/useBlockConversion.tsx
> +
이 로직도 `if 문`이 반복되고 있는데,
오브젝트로 관리해 볼 수 있는 여지가 있을 것 같아요!!

2020-12-02 04:24 UTC, skid901 commented on frontend/src/utils/regex.ts
> +};
정규식 별도로 분리한 것 좋은 것 같아요!!

2020-12-02 04:26 UTC, domino8788 approved these changes
수고하셨습니다.

2020-12-02 04:26 UTC, domino8788 commented on frontend/src/App.tsx
> +  }, []);
해결방법을 찾으셨네요.
감사합니다!

2020-12-02 04:32 UTC, YiSoJeong commented on frontend/src/hooks/useBlockConversion.tsx
> +
네네 이거 리뷰어 참고사항에 올린 부분인데 PR 사이즈 때문에 일단 보류했습니다 😌 오래기다리시게 하는 것 같네요🥺

2020-12-02 04:36 UTC, skid901 approved these changes
고생하셨습니다 ^^7

2020-12-02 05:05 UTC, merged

2020-12-03 05:04 UTC, crongro reviewed
짧게 몇 줄 남겨요~
리뷰를 하다보니 질문을 몇 개 남기게 됐네요 ㅎ

2020-12-03 05:04 UTC, crongro commented on frontend/src/hooks/useBlockConversion.tsx
> +const useBlockConversion = (blockDTO: Block) => {
일반 컴포넌트와 같이 렌더링결과를 반환하는데, 
분류는 커스텀훅으로 되어 있어요. 
어떤 이유가 있을까요?

2020-12-03 05:04 UTC, crongro commented on frontend/src/hooks/useBlockConversion.tsx
> +    if (regex.h2.test(content.current))
코드의 표현이 약간 부자연스럽다고 개인적으로 느껴지는데요.
content.current 를 변수에 미리 저장해두고, 그 결과가 A랑 같니? 아니면  B랑 같니? 
이런식으로 코드를 표현하면 어떨까 ? 생각되네요.

2020-12-03 05:22 UTC, YiSoJeong commented on frontend/src/hooks/useBlockConversion.tsx
> +const useBlockConversion = (blockDTO: Block) => {
처음에는 컴포넌트의 로직만 외부로 분리하려고 했는데 작성하다 보니 반환 값을 아예  컴포넌트로 넘겨주게 되었습니다 😂 현재는 다시 컴포넌트 폴더에 이동시켜 작업중이고 추후에 재사용 가능한 로직이 있으면 커스텀 훅으로 외부화 시킬 예정입니다 :)

2020-12-03 05:40 UTC, domino8788 commented on frontend/src/components/molecules/BlockComponent/BlockComponent.tsx
> +  const [hoverId, setHoverId] = useRecoilState(hoverState);
blockState, focusState, hoverState 의 경우 전역으로 관리되는 상태 입니다.
blockState의 경우 atomFamily로 생성되어 key 값으로 blockState에 저장된 value를 가져올 수 있습니다.
`const [block, setBlock] = useRecoilState(blockState(blockDTO.id));`
위 코드에서 컴포넌트 초기화 동시에 매개변수로 자신의 id를 넘기면 setBlock에 의한 초기화 이전이므로 block에 null 값이 할당 됩니다.
랜더링이 완료되면 useEffect를 통해 `setBlock(BlockDTO)` 가 실행되고 BlockState에 Block의 id를 key 값으로 Block에 대한 정보가 value로 묶여 저장 됩니다.
이후 block의 상태값을 읽거나 조정하기 위해서는 해당 블록의 id만 알아내면 접근이 가능 합니다.
Block Component가 destroy 되면 value를 null로 초기화하게 했습니다.

focusState는 현재 focus가 잡혀있는 Block의 id 를 관리하는 상태 입니다.

hoverState는 현재 hover 되어있는 Block의 id를 관리하는 상태 입니다.

useState를 사용할 경우 해당 값들을 필요로하는 컴포넌트들의 조상에 각 상태들을 생성하고 props로 넘겨주는 구조가 되어 초기화 로직이 길어졌을 것으로 예상 됩니다.

useContext와 Provider로 이를 대체할 경우 id를 key 값으로 Block 정보를 반환하는 로직을 직접 구현해야 했겠지만 atomFamily를 이용해서 해당 로직이 자동 구현 됩니다.

2020-12-03 05:43 UTC, YiSoJeong commented on frontend/src/hooks/useBlockConversion.tsx
> +    if (regex.h2.test(content.current))
이벤트로 받아온 값을 저장해주는 부분이 없네요😵
수정하다 빼먹었나 봅니다. 지적 감사합니다 :)

2020-12-03 07:15 UTC, crongro commented on frontend/src/hooks/useBlockConversion.tsx
> +const useBlockConversion = (blockDTO: Block) => {
아하 넵!

2020-12-03 07:17 UTC, crongro commented on frontend/src/components/molecules/BlockComponent/BlockComponent.tsx
> +  const [hoverId, setHoverId] = useRecoilState(hoverState);
와 자세한 설명 너무 고마워요. 많이 배우고 갑니다. 👍